[package]
name = "rpc-eth-api"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfx-rpc-eth-types = { workspace = true }
jsonrpsee = { version = "0.24.4", features = ["server", "macros"] }
cfx-types = { workspace = true }
cfx-rpc-primitives = { workspace = true }
alloy-rpc-types-trace = { workspace = true }
