# Use workspace section to allow test all cases under root folder (cargo test --all).
[workspace]
members = [
    "crates/cfx_bytes",
    "crates/cfx_types",
    "crates/cfx_addr",
    "crates/cfx_math",
    "crates/cfx_utils",
    "crates/stratum",
    "crates/accounts",
    "crates/blockgen",
    "crates/cfx_key",
    "crates/cfx_store",
    "crates/dbs/db",
    "crates/dbs/kvdb-rocksdb",
    "crates/dbs/db-errors",
    "crates/network",
    "crates/primitives",
    "crates/secret_store",
    "crates/transactiongen",
    "bins/cfx_store",
    "bins/cfx_key",
    "bins/conflux",
    "crates/core/core",
    "crates/core/execute-helper",
    "crates/core/executor",
    "crates/core/internal_common",
    "crates/core/packing-pool",
    "crates/core/parameters",
    "crates/core/statedb",
    "crates/core/storage",
    "crates/core/vm-interpreter",
    "crates/core/vm-types",
    "crates/util/cfx-vm-tracer-derive",
    "crates/util/dag",
    "crates/util/delegate",
    "crates/util/heap-map",
    "crates/util/hibitset",
    "crates/util/io",
    "crates/util/link-cut-tree",
    "crates/util/log_device",
    "crates/util/malloc_size_of",
    "crates/util/malloc_size_of_derive",
    "crates/util/memory-cache",
    "crates/util/metrics",
    "crates/util/priority-send-queue",
    "crates/util/random_crash",
    "crates/util/runtime",
    "crates/util/sha3-macro",
    "crates/util/solidity-abi",
    "crates/util/solidity-abi-derive",
    "crates/util/throttling",
    "crates/util/treap-map",
    "crates/util/version"
]

[patch.crates-io]
sqlite3-sys = { git = "https://github.com/Conflux-Chain/sqlite3-sys.git", rev = "1de8e5998f7c2d919336660b8ef4e8f52ac43844" }

[profile.test]
debug-assertions = true

[profile.test.package]
parity-secp256k1 = { opt-level = 3 }

[profile.bench]
debug-assertions = true
overflow-checks = true

[profile.release]
overflow-checks = true
# Temporarily run with debug assertion before main-net release.
debug-assertions = true