[package]
description = "Conflux core parameters library"
homepage = "https://www.confluxnetwork.org"
license = "GPL-3.0"
name = "cfx-parameters"
version = "1.0.0"
edition = "2018"

[dependencies]
cfx-types = { path = "../../crates/cfx_types" }
cfx-vm-types = { path = "../vm-types" }
cfxkey = { path = "../../crates/cfx_key" }
cfx-bytes = { path = "../../crates/cfx_bytes" }

lazy_static = "1.4"
hex-literal = "0.4.1"
rustc-hex = "2.1"