[package]
name = "rpc-types-trace"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
alloy-primitives = { workspace = true, features = ["rlp", "serde"] }
cfx-types = { path = "../cfx_types" }
cfx-bytes = { path = "../cfx_bytes" }
cfx-serde = { path = "../serde" }
similar-asserts = "1.5"