[package]
name = "cfx-rpc-builder"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive"]  }
strum = { workspace = true, features = ["derive"]  }
alloy-primitives = { workspace = true}
thiserror = { workspace = true }

jsonrpc-core ={ workspace = true}
jsonrpsee-core = { workspace = true }
jsonrpsee-types = { workspace = true }
jsonrpsee = { workspace = true, features = ["server"] }
tower = { workspace = true, features = ["full"] }
http.workspace = true
pin-project = { workspace = true }
rand = { workspace = true }
cfx-rpc = { workspace = true }
cfx-rpc-eth-api = { workspace = true }
cfxcore = { workspace = true }
cfx-types = { workspace = true }
cfx-rpc-eth-types = { workspace = true }
cfx-rpc-cfx-types = { workspace = true }
throttling = { workspace = true }
cfx-util-macros = { workspace = true }
log = { workspace = true }
cfx-rpc-utils = { workspace = true }
cfx-rpc-middlewares = { workspace = true }
futures-util = { workspace = true, features = ["io", "async-await-macro"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }