[package]
description = "Conflux Keys Generator"
name = "cfxkey"
version = "0.3.0"
authors = ["Conflux Foundation"]

[dependencies]
cfx-types = { workspace = true }
edit-distance = "2.0"
parity-crypto = { workspace = true }
parity-secp256k1 = { workspace = true }
lazy_static = "1.4"
log = "0.4"
parity-wordlist = { workspace = true }
quick-error = "1.2.2"
rand = "0.7"
rustc-hex = "2.1"
serde = "1.0"
serde_derive = "1.0"
tiny-keccak = "1.4"
zeroize = "1.0.0"
malloc_size_of_derive = { workspace = true }
malloc_size_of = { workspace = true }
docopt = "1.0"
env_logger = "0.5"
panic_hook = { workspace = true }
threadpool = "1.7"

