[package]
description = "Parity Ethereum Key Management"
name = "cfxstore"
version = "0.2.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
log = "0.4"
libc = { workspace = true }
rand = { workspace = true }
cfx-types = { workspace = true }
cfxkey = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
rustc-hex = { workspace = true }
tiny-keccak = "1.4"
time = "0.1.34"
parking_lot = { workspace = true }
parity-crypto = { workspace = true, features = ["publickey"] }
dir = { workspace = true }
smallvec = "1.4"
parity-wordlist = { workspace = true }
tempdir = "0.3"

[dev-dependencies]
matches = "0.1"
