name: "Setup Docker Environment"
description: "Sets up Docker with caching and builds the base image"
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-base-${{ hashFiles('.github/dockers/base.Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-base-

    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .github/dockers/base.Dockerfile
        load: true
        tags: base-builder:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: false
