[package]
description = "Conflux IO library"
homepage = "http://conflux-chain.io"
license = "GPL-3.0"
name = "io"
version = "0.1.0"
edition = "2021"

[dependencies]
fnv = { workspace = true }
mio = { workspace = true }
crossbeam-deque = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
slab = { workspace = true }
num_cpus = { workspace = true }
timer = { workspace = true }
time = { workspace = true }
metrics = { workspace = true }
lazy_static = { workspace = true }

