name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and generate docs
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/docs.Dockerfile
          load: true
          tags: doc-builder:latest

      - name: Generate documentation
        run: |
          docker run --rm -v $(pwd):/app -w /app doc-builder:latest \
            bash -c "RUSTDOCFLAGS='--enable-index-page -Z unstable-options' cargo +nightly-2024-01-29 doc --no-deps"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
