name: Lint

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cargo Cache
        uses: ./.github/actions/setup-cargo-cache

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            target/release/deps
            target/release/.fingerprint
            target/release/build
            !target/release/build/**/out
            !target/release/incremental
            !target/release/.cargo-lock
          key: ${{ runner.os }}-build-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-release-

      - name: Setup Docker
        uses: ./.github/actions/setup-docker

      - name: Check format and run clippy
        run: |
          docker run --rm \
          -v $(pwd):/app \
          -v ~/.cargo/registry:/root/.cargo/registry \
          -v ~/.cargo/git:/root/.cargo/git \
          -e RUST_BACKTRACE=1 \
          -e RUSTFLAGS="-g" \
          -w /app base-builder:latest \
          bash -c "./cargo_fmt.sh --install && ./cargo_fmt.sh -- --check && cargo clippy --release --all -- -A warnings"

      - name: Ensure cache files are accessible
        run: |
          sudo chown -R $(id -u):$(id -g) target/release
          sudo chown -R $(id -u):$(id -g) ~/.cargo
