name: Lint

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android

      - name: Cache Cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-deps-

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ hashFiles('.github/dockers/base.Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/dockers/base.Dockerfile
          load: true
          tags: base-builder:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Check format and run clippy
        run: |
          docker run --rm \
          -v $(pwd):/app \
          -v ~/.cargo/registry:/root/.cargo/registry \
          -v ~/.cargo/git:/root/.cargo/git \
          -e RUST_BACKTRACE=1 \
          -e RUSTFLAGS="-g" \
          -w /app base-builder:latest \
          bash -c "./cargo_fmt.sh --install && ./cargo_fmt.sh -- --check && cargo clippy --release --all -- -A warnings"
