name: Tests

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"

jobs:
  check-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          key: "check-crates"
          workspaces: ". -> target/debug"
          shared-key: "debug-cache"

      - name: Setup Docker
        uses: ./.github/actions/setup-docker

      - name: Check individual crates
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -v ~/.cargo/registry:/root/.cargo/registry \
            -v ~/.cargo/git:/root/.cargo/git \
            -e RUST_BACKTRACE=1 \
            -w /app base-builder:latest \
            dev-support/check-crates.sh

      - name: Ensure cache files are accessible
        run: |
          sudo chown -R $(id -u):$(id -g) target/debug 
          sudo chown -R $(id -u):$(id -g) ~/.cargo

  workspace-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android

      - uses: Swatinem/rust-cache@v2
        with:
          key: "release-tests"
          shared-key: "target-release-cache"
          workspaces: ". -> target/release"
          cache-on-failure: "true"

      - name: Setup Docker
        uses: ./.github/actions/setup-docker

      - name: Run workspace tests
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -v ~/.cargo/registry:/root/.cargo/registry \
            -v ~/.cargo/git:/root/.cargo/git \
            -e RUST_BACKTRACE=1 \
            -w /app base-builder:latest \
            cargo nextest run --no-fail-fast --release --workspace

      - name: Ensure cache files are accessible
        run: |
          sudo chown -R $(id -u):$(id -g) target/release 
          sudo chown -R $(id -u):$(id -g) ~/.cargo

  cfx-addr-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android

      - uses: Swatinem/rust-cache@v2
        with:
          key: "cfx-addr-tests"
          workspaces: ". -> target/debug"
          shared-key: "debug-cache"

      - name: Setup Docker
        uses: ./.github/actions/setup-docker

      - name: Run cfx-addr
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -v ~/.cargo/registry:/root/.cargo/registry \
            -v ~/.cargo/git:/root/.cargo/git \
            -e RUST_BACKTRACE=1 \
            -w /app base-builder:latest \
            cargo nextest run --no-fail-fast -p cfx-addr --no-default-features

      - name: Ensure cache files are accessible
        run: |
          sudo chown -R $(id -u):$(id -g) target/debug 
          sudo chown -R $(id -u):$(id -g) ~/.cargo
