name: Tests

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.json"
      - "*.sol"
      - "docs/**"
      - ".gitignore"
      - ".travis.yml"
      - "cargo_fmt.sh"
      - "CODEOWNERS"

jobs:
  check-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cargo Cache
        uses: ./.github/actions/setup-cargo-cache

      - name: Cache debug build artifacts
        uses: actions/cache@v4
        with:
          path: |
            target/debug/deps
            target/debug/.fingerprint
            target/debug/build
            !target/debug/build/**/out
            !target/debug/deps/librust_verify*
            !target/debug/incremental
            !target/debug/.cargo-lock
          key: ${{ runner.os }}-build-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-debug-

      - name: Setup Docker
        uses: ./.github/actions/setup-docker

      - name: Check individual crates
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -v ~/.cargo/registry:/root/.cargo/registry \
            -v ~/.cargo/git:/root/.cargo/git \
            -e RUST_BACKTRACE=1 \
            -w /app base-builder:latest \
            dev-support/check-crates.sh

      - name: Ensure cache files are accessible
        run: |
          sudo chown -R $(id -u):$(id -g) target/debug 
          sudo chown -R $(id -u):$(id -g) ~/.cargo

  workspace-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android

      - name: Setup Cargo Cache
        uses: ./.github/actions/setup-cargo-cache

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            target/release/deps
            target/release/.fingerprint
            target/release/build
            !target/release/build/**/out
            !target/release/incremental
            !target/release/.cargo-lock
          key: ${{ runner.os }}-build-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-release-


      - name: Setup Docker
        uses: ./.github/actions/setup-docker

      - name: Run workspace tests
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -v ~/.cargo/registry:/root/.cargo/registry \
            -v ~/.cargo/git:/root/.cargo/git \
            -e RUST_BACKTRACE=1 \
            -w /app base-builder:latest \
            cargo nextest run --no-fail-fast --release --workspace

      - name: Ensure cache files are accessible
        run: |
          sudo chown -R $(id -u):$(id -g) target/release 
          sudo chown -R $(id -u):$(id -g) ~/.cargo

  cfx-addr-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android

      - name: Setup Cargo Cache
        uses: ./.github/actions/setup-cargo-cache

      - name: Cache debug build artifacts
        uses: actions/cache@v4
        with:
          path: |
            target/debug/deps
            target/debug/.fingerprint
            target/debug/build
            !target/debug/build/**/out
            !target/debug/deps/librust_verify*
            !target/debug/incremental
            !target/debug/.cargo-lock
          key: ${{ runner.os }}-build-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-debug-

      - name: Setup Docker
        uses: ./.github/actions/setup-docker

      - name: Run cfx-addr
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -v ~/.cargo/registry:/root/.cargo/registry \
            -v ~/.cargo/git:/root/.cargo/git \
            -e RUST_BACKTRACE=1 \
            -w /app base-builder:latest \
            cargo nextest run --no-fail-fast -p cfx-addr --no-default-features

      - name: Ensure cache files are accessible
        run: |
          sudo chown -R $(id -u):$(id -g) target/debug 
          sudo chown -R $(id -u):$(id -g) ~/.cargo
